#!/usr/bin/env -S deno run --allow-read --allow-write --allow-env
// Installs a `searchman` launcher into a bin dir. The launcher execs the
// binary built by `deno task build`; nothing is copied out of the repo.
// Modeled on wm-mini's scripts/install.ts.

const marker = "generated by searchman installer";
const sep = Deno.build.os === "windows" ? "\\" : "/";
const binaryName = Deno.build.os === "windows" ? "searchman.exe" : "searchman";
const scriptDir = import.meta.dirname ?? sep;
const repoRoot = scriptDir.slice(0, scriptDir.lastIndexOf(sep));

function home(): string {
  return Deno.env.get("HOME") ?? Deno.env.get("USERPROFILE") ?? "~";
}

function expand(path: string): string {
  if (path === "~") return home();
  if (path.startsWith("~/") || path.startsWith("~\\")) {
    return join(home(), path.slice(2));
  }
  return path;
}

function defaultBinDir(): string {
  const denoInstallRoot = Deno.env.get("DENO_INSTALL_ROOT");
  if (denoInstallRoot) return join(expand(denoInstallRoot), "bin");
  if (Deno.build.os === "windows") return join(home(), ".deno", "bin");
  return join(home(), ".local", "bin");
}

function launcherTargets(
  binDir: string,
): { path: string; content: string; executable: boolean }[] {
  if (Deno.build.os === "windows") {
    return [{
      path: join(binDir, "searchman.cmd"),
      content:
        `@echo off\r\nrem ${marker}\r\n"${join(repoRoot, binaryName)}" %*\r\n`,
      executable: false,
    }];
  }
  // Single-quote the path so spaces and other shell metacharacters survive.
  const quotedBinary = `'${join(repoRoot, binaryName).replaceAll("'", "'\\''")}'`;
  return [{
    path: join(binDir, "searchman"),
    content: `#!/usr/bin/env sh\n# ${marker}\nexec ${quotedBinary} "$@"\n`,
    executable: true,
  }];
}

function join(...parts: string[]): string {
  const [first = "", ...rest] = parts;
  return rest.reduce(
    (acc, part) =>
      `${acc.replace(/[\\/]+$/, "")}${sep}${part.replace(/^[\\/]+/, "")}`,
    first,
  );
}

async function readIfExists(path: string): Promise<string | undefined> {
  try {
    return await Deno.readTextFile(path);
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return undefined;
    throw error;
  }
}

async function main(): Promise<number> {
  const binary = join(repoRoot, binaryName);
  const stat = await Deno.stat(binary).catch(() => undefined);
  if (!stat?.isFile) {
    console.error(`no ${binary} in this repo; run \`deno task build\` first`);
    return 1;
  }

  const binDir = defaultBinDir();
  await Deno.mkdir(binDir, { recursive: true });

  for (const target of launcherTargets(binDir)) {
    const existing = await readIfExists(target.path);
    if (existing && !existing.includes(marker)) {
      console.error(`refusing to overwrite existing ${target.path}`);
      console.error("remove it first, then rerun `deno task install`");
      return 1;
    }
    await Deno.writeTextFile(target.path, target.content);
    if (target.executable) await Deno.chmod(target.path, 0o755);
    console.log(`installed searchman -> ${target.path}`);
    console.log(`launcher target: ${binary}`);
  }

  const pathDirs = (Deno.env.get("PATH") ?? "").split(
    Deno.build.os === "windows" ? ";" : ":",
  );
  if (!pathDirs.some((dir) => dir.replace(/[\\/]+$/, "") === binDir)) {
    console.error(
      `${binDir} is not on PATH; add it to your shell config to use searchman`,
    );
  }
  return 0;
}

if (import.meta.main) Deno.exit(await main());
